### ISSUE TITLE
'libxml/xmlreader.h' file not found

### ISSUE THREAD

**Issue by Heodel** [Naova/NaovaRelease#1]
Dear Naova Official:
We have downloaded the code release zip and compiled it used command "make" on Ubuntu 18.04 LTS. But we met some problems.
The first one is when I compiled it, it warned us we didn't install clang++-4.0, then we used command "apt install clang++-4.0" to install it,  and make again.
Then we met another error:

..Util/SimRobot/Src/SimRobotCore2/Parser/Reader.cpp
../../Util/SimRobot/Src/SimRobotCore2/Parser/Reader.cpp:7:10: fatal error: 
      'libxml/xmlreader.h' file not found
#include <libxml/xmlreader.h>
         ^~~~~~~~~~~~~~~~~~~~
..Util/SimRobot/Src/SimRobotCore2/Tools/Texture.cpp
..Util/SimRobot/Src/SimRobotCore2/Tools/OpenGLTools.cpp
1 error generated.

**Comment by vgirardeau** [comment]
Hi, did you follow the getting started from CodeRelease2017.pdf in the BHuman repo ? https://github.com/bhuman/BHumanCodeRelease/tree/coderelease2017
